export const communes = [
  {
    value: 165,
    label: 'Albertslund',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 201,
    label: 'Allerød',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 420,
    label: 'Assens',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 151,
    label: 'Ballerup',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 530,
    label: 'Billund',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 400,
    label: 'Bornholm',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 153,
    label: 'Brøndby',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 810,
    label: 'Brønderslev',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 155,
    label: 'Dragør',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 240,
    label: 'Egedal',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 561,
    label: 'Esbjerg',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 563,
    label: 'Fanø',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 710,
    label: 'Favrskov',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 320,
    label: 'Faxe',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 210,
    label: 'Fredensborg',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 607,
    label: 'Fredericia',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 147,
    label: 'Frederiksberg',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 813,
    label: 'Frederikshavn',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 250,
    label: 'Frederikssund',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 190,
    label: 'Furesø',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 430,
    label: 'Faaborg-Midtfyn',
    parent: 84733,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 157,
    label: 'Gentofte',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 159,
    label: 'Gladsaxe',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 161,
    label: 'Glostrup',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 253,
    label: 'Greve',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 270,
    label: 'Gribskov',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 376,
    label: 'Guldborgsund',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 510,
    label: 'Haderslev',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 260,
    label: 'Halsnæs',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 766,
    label: 'Hedensted',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 217,
    label: 'Helsingør',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 163,
    label: 'Herlev',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 657,
    label: 'Herning',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 219,
    label: 'Hillerød',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 860,
    label: 'Hjørring',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 316,
    label: 'Holbæk',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 661,
    label: 'Holstebro',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 615,
    label: 'Horsens',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 167,
    label: 'Hvidovre',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 169,
    label: 'Høje-Taastrup',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 223,
    label: 'Hørsholm',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 756,
    label: 'Ikast-Brande',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 183,
    label: 'Ishøj',
    parent: 84982,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 849,
    label: 'Jammerbugt',
    parent: 84712,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 326,
    label: 'Kalundborg',
    parent: 84979,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 440,
    label: 'Kerteminde',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 621,
    label: 'Kolding',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 101,
    label: 'København',
    parent: 84982,
    councilType: 'borgerrepræsentation',
    councilTypePlural: 'borgerrepræsentationen',
  },
  {
    value: 259,
    label: 'Køge',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 482,
    label: 'Langeland',
    parent: 84733,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 350,
    label: 'Lejre',
    parent: 84979,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 665,
    label: 'Lemvig',
    parent: 84713,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 360,
    label: 'Lolland',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 173,
    label: 'Lyngby-Taarbæk',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 825,
    label: 'Læsø',
    parent: 84712,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 846,
    label: 'Mariagerfjord',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 410,
    label: 'Middelfart',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 773,
    label: 'Morsø',
    parent: 84712,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 707,
    label: 'Norddjurs',
    parent: 84713,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 480,
    label: 'Nordfyns',
    parent: 84733,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 450,
    label: 'Nyborg',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 370,
    label: 'Næstved',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 727,
    label: 'Odder',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 461,
    label: 'Odense',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 306,
    label: 'Odsherred',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 730,
    label: 'Randers',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 840,
    label: 'Rebild',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 760,
    label: 'Ringkøbing-Skjern',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 329,
    label: 'Ringsted',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 265,
    label: 'Roskilde',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 230,
    label: 'Rudersdal',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 175,
    label: 'Rødovre',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 741,
    label: 'Samsø',
    parent: 84713,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 740,
    label: 'Silkeborg',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 746,
    label: 'Skanderborg',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 779,
    label: 'Skive',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 330,
    label: 'Slagelse',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 269,
    label: 'Solrød',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 340,
    label: 'Sorø',
    parent: 84979,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 336,
    label: 'Stevns',
    parent: 84979,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 671,
    label: 'Struer',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 479,
    label: 'Svendborg',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 706,
    label: 'Syddjurs',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 540,
    label: 'Sønderborg',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 787,
    label: 'Thisted',
    parent: 84712,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 550,
    label: 'Tønder',
    parent: 84733,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 185,
    label: 'Tårnby',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 187,
    label: 'Vallensbæk',
    parent: 84982,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 573,
    label: 'Varde',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 575,
    label: 'Vejen',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 630,
    label: 'Vejle',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 820,
    label: 'Vesthimmerlands',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 791,
    label: 'Viborg',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 390,
    label: 'Vordingborg',
    parent: 84979,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 492,
    label: 'Ærø',
    parent: 84733,
    councilType: 'kommunalbestyrelse',
    councilTypePlural: 'kommunalbestyrelsen',
  },
  {
    value: 580,
    label: 'Aabenraa',
    parent: 84733,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 851,
    label: 'Aalborg',
    parent: 84712,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
  {
    value: 751,
    label: 'Aarhus',
    parent: 84713,
    councilType: 'byråd',
    councilTypePlural: 'byrådet',
  },
];
